#!/usr/bin/env python3
"""
HTTP API Testing - Generated by TigerHill

Test an HTTP API endpoint with request/response validation
"""

import pytest
import requests
from tigerhill.adapters.http_adapter import HTTPAdapter
from tigerhill.assertions import assert_http_status
from tigerhill.storage.trace_store import TraceStore


class TestUserPost:
    """HTTP API Testing Test Suite"""

    @pytest.fixture
    def adapter(self):
        """Create HTTP adapter"""
        return HTTPAdapter(
            base_url="http://localhost:3000/api/users",
            timeout=30
        )

    @pytest.fixture
    def trace_store(self, tmp_path):
        """Create trace store for recording"""
        return TraceStore(storage_path=str(tmp_path))

    def test_user_post(self, adapter, trace_store):
        """Test HTTP API Testing"""

        # Start trace
        trace_id = trace_store.start_trace(
            agent_name="user-post",
            task_id="api-test-user-post",
            metadata={
                "url": "http://localhost:3000/api/users",
                "method": "POST"
            }
        )

        try:
            # Prepare request
            request_body = {'name': 'test', 'email': 'test@example.com'}
            # Execute request
            response = adapter.execute(
                trace_id=trace_id,
                method="POST",
                endpoint="/",
json=request_body,
)

            # Validate response
            assert_http_status(
                response,
                expected_status=201,
                trace_id=trace_id
            )

            # Additional validations
            assert response.text is not None, "Response body should not be None"

            # Try to parse as JSON if content type indicates JSON
            content_type = response.headers.get('Content-Type', '')
            if 'application/json' in content_type:
                try:
                    json_data = response.json()
                    trace_store.write_event(
                        {
                            "type": "validation",
                            "message": "Response is valid JSON",
                            "data": json_data
                        },
                        trace_id=trace_id
                    )
                except ValueError as e:
                    trace_store.write_event(
                        {
                            "type": "warning",
                            "message": f"Failed to parse JSON response: {e}"
                        },
                        trace_id=trace_id
                    )

            print(f"✅ Test passed: user-post")

        except Exception as e:
            trace_store.write_event(
                {
                    "type": "error",
                    "error_message": str(e),
                    "error_type": type(e).__name__
                },
                trace_id=trace_id
            )
            raise

        finally:
            # End trace
            trace_store.end_trace(trace_id)


if __name__ == "__main__":
    pytest.main([__file__, "-v", "-s"])