#!/usr/bin/env python3
"""
REST CRUD Testing - Generated by TigerHill

Test complete CRUD operations (Create, Read, Update, Delete) on a REST API
"""

import pytest
import requests
from tigerhill.adapters.http_adapter import HTTPAdapter
from tigerhill.assertions import assert_http_status
from tigerhill.storage.trace_store import TraceStore, EventType


class TestPostCrud:
    """REST CRUD Testing Test Suite"""

    @pytest.fixture
    def adapter(self):
        """Create HTTP adapter"""
        return HTTPAdapter(
            base_url="http://localhost:3000",
            timeout=30
        )

    @pytest.fixture
    def trace_store(self, tmp_path):
        """Create trace store for recording"""
        return TraceStore(storage_path=str(tmp_path))

    def test_crud_operations(self, adapter, trace_store):
        """Test full CRUD cycle"""

        # Start trace
        trace_id = trace_store.start_trace(
            agent_name="post-crud",
            task_id="crud-test-post-crud",
            metadata={
                "base_url": "http://localhost:3000",
                "resource": "post"
            }
        )

        created_id = None

        try:
            # === CREATE ===
            create_data = {
                "name": "Test post",
                "description": "Created by TigerHill test"
            }

            trace_store.write_event(
                {"type": "operation", "operation": "CREATE"},
                trace_id=trace_id
            )

            create_response = adapter.execute(
                trace_id=trace_id,
                method="POST",
                endpoint="/api/posts",
                json=create_data
            )

            assert_http_status(create_response, 201, trace_id=trace_id)
            created_data = create_response.json()
            created_id = created_data.get("id")
            assert created_id is not None, "Created resource should have an ID"

            print(f"✅ CREATE: Created post with ID {created_id}")

            # === READ ===
            trace_store.write_event(
                {"type": "operation", "operation": "READ"},
                trace_id=trace_id
            )

            read_response = adapter.execute(
                trace_id=trace_id,
                method="GET",
                endpoint=f"/api/posts/{created_id}"
            )

            assert_http_status(read_response, 200, trace_id=trace_id)
            read_data = read_response.json()
            assert read_data.get("id") == created_id

            print(f"✅ READ: Retrieved post {created_id}")

            # === UPDATE ===
            trace_store.write_event(
                {"type": "operation", "operation": "UPDATE"},
                trace_id=trace_id
            )

            update_data = {
                "name": "Updated post",
                "description": "Updated by TigerHill test"
            }

            update_response = adapter.execute(
                trace_id=trace_id,
                method="PUT",
                endpoint=f"/api/posts/{created_id}",
                json=update_data
            )

            assert_http_status(update_response, 200, trace_id=trace_id)

            print(f"✅ UPDATE: Updated post {created_id}")

            # === DELETE ===
            trace_store.write_event(
                {"type": "operation", "operation": "DELETE"},
                trace_id=trace_id
            )

            delete_response = adapter.execute(
                trace_id=trace_id,
                method="DELETE",
                endpoint=f"/api/posts/{created_id}"
            )

            assert_http_status(delete_response, 204, trace_id=trace_id)

            print(f"✅ DELETE: Deleted post {created_id}")

            # Verify deletion
            verify_response = adapter.execute(
                trace_id=trace_id,
                method="GET",
                endpoint=f"/api/posts/{created_id}"
            )

            assert verify_response.status_code == 404, \
                "Deleted resource should return 404"

            print(f"✅ CRUD cycle completed successfully")

        except Exception as e:
            trace_store.write_event(
                {
                    "type": "error",
                    "error_message": str(e),
                    "error_type": type(e).__name__
                },
                trace_id=trace_id,
                event_type=EventType.ERROR
            )
            raise

        finally:
            # End trace
            trace_store.end_trace(trace_id)


if __name__ == "__main__":
    pytest.main([__file__, "-v", "-s"])